application: html5media
version: 1-1-5
runtime: python
api_version: 1

default_expiration: "365d"

handlers:
- url: /(.+?)\.txt
  static_files: www/\1.txt
  upload: www/(.+?)\.txt
- url: /(.+?)\.js
  static_files: www/\1.js
  upload: www/(.+?)\.js
- url: /(.+?)\.swf
  static_files: www/\1.swf
  upload: www/(.+?)\.swf
- url: /.*
  script: main.py